// Code generated by "stringer -output token_type_string.go -type=TokenType"; DO NOT EDIT.

package json2go

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ILLEGAL-1]
	_ = x[NEWLINE-2]
	_ = x[INDENT-3]
	_ = x[NUMBER-4]
	_ = x[DECIMAL-5]
	_ = x[STRING-6]
	_ = x[BOOL-7]
	_ = x[NULL-8]
	_ = x[COLON-9]
	_ = x[COMMA-10]
	_ = x[LBRACE-11]
	_ = x[RBRACE-12]
	_ = x[LBRACKET-13]
	_ = x[RBRACKET-14]
	_ = x[COMMENTLINE-15]
	_ = x[COMMENTBLOCK-16]
}

const _TokenType_name = "EOFILLEGALNEWLINEINDENTNUMBERDECIMALSTRINGBOOLNULLCOLONCOMMALBRACERBRACELBRACKETRBRACKETCOMMENTLINECOMMENTBLOCK"

var _TokenType_index = [...]uint8{0, 3, 10, 17, 23, 29, 36, 42, 46, 50, 55, 60, 66, 72, 80, 88, 99, 111}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
